name: verigender
description: "A new Flutter project."
# Prevents accidental publishing to pub.dev. Remove this line if you wish to publish.
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev.

# Defines the version and build number for your application.
version: 1.0.0+1

# SDK environment
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Adds the Cupertino Icons font for iOS-style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package for better coding practices.
  flutter_lints: ^4.0.0

flutter:
  # Ensures Material Design icons are included with the application.
  uses-material-design: true

  # To add assets, specify them under this section.
  assets:
    - lib/assets/VeriGender.png
  # Additional asset examples can be added as needed, such as images or JSON files.

  # To add custom fonts to your application, specify them under fonts:
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700

  # For resolution-aware images, refer to the documentation on Flutter's image assets.
